/*4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
public class Q4 {
    public static char findDiff(String s, String t) {
        char res = 0;
        for (char c : s.toCharArray()) res ^= c;
        for (char c : t.toCharArray()) res ^= c;
        return res;
    }

    public static void main(String[] args) {
        System.out.println(findDiff("abcd", "abcde")); // e
        System.out.println(findDiff("", "y"));         // y
    }
}

/*import java.util.*;

public class Q4 {
    public static char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap<>();

        // Count each character in s
        for (char c : s.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }

        // Subtract counts using t
        for (char c : t.toCharArray()) {
            if (!map.containsKey(c) || map.get(c) == 0) {
                return c; // This is the extra character
            }
            map.put(c, map.get(c) - 1);
        }

        return ' '; // Should never reach here
    }

    public static void main(String[] args) {
        String s1 = "abcd";
        String t1 = "abcde";
        System.out.println("Extra letter: " + findTheDifference(s1, t1)); // Output: e

        String s2 = "";
        String t2 = "y";
        System.out.println("Extra letter: " + findTheDifference(s2, t2)); // Output: y
    }
}
*/
